vtrue-master/user/urls.py
from django.urls import path,include
from . import views
app_name='user'
urlpatterns = [
    path('register/',views.signup,name='signup'),
    path('login/',views.signin.as_view(),name='signin'),
]

vtrue-master/vtrue/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/',include('website.urls'), name='website'),
    path('user/',include('user.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vtrue-master/website/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
app_name='website'
urlpatterns = [
    path('main/', views.main, name='main'),
    path('intro/',views.intro,name='intro'),
    path('news/',views.news,name='news'),
    path('company/',views.company,name='company'),
    path('feedback/',views.feedback,name='feedback'),
    path('register/',views.register,name='register'),
    path('sign-in/',views.sign_in,name='sign-in'),
    path('count/',views.count,name='count-history'),
    path('check/',views.check.as_view(),name='check'),
    path(r'^export/xls/$', views.export_users_xls, name='export_users_xls'),
]

vtrue-master/website/models.py
from djongo import models
import datetime
# Create your models here.

class SMSHistory(models.Model):
    ThoiGian = models.DateField(default=datetime.date.today,null=True,blank=True)
    SoDienThoai = models.CharField(max_length=100,null=True,blank=True)
    SeriNo = models.CharField(max_length=100,null=True,blank=True)
    Count = models.IntegerField(default=0,null=True,blank=True)
class WebHistory(models.Model):
    ThoiGian = models.DateField(default=datetime.date.today,null=True,blank=True)
    DiaChiIP = models.CharField(max_length=100,null=True,blank=True)
    SoDienThoai = models.CharField(max_length=100,null=True,blank=True)
    SeriNo = models.CharField(max_length=100,null=True,blank=True)
    Count = models.IntegerField(default=0,null=True,blank=True)
class AppHistory(models.Model):
    ThoiGian = models.DateField(default=datetime.date.today,null=True,blank=True)
    DiaChiIP = models.CharField(max_length=100,null=True,blank=True)
    SoDienThoai = models.CharField(max_length=100,null=True,blank=True)
    SeriNo = models.CharField(max_length=100,null=True,blank=True)
    Count = models.IntegerField(default=0,null=True,blank=True)
class CallHistory(models.Model):
    ThoiGian = models.DateField(default=datetime.date.today,null=True,blank=True)
    SoDienThoai = models.CharField(max_length=100,null=True,blank=True)
    SeriNo = models.CharField(max_length=100,null=True,blank=True)
    Count = models.IntegerField(default=0,null=True,blank=True)
class History(models.Model):
    MaTem = models.CharField(max_length=100,null=True,blank=True)
    MaSP = models.CharField(max_length=100,null=True,blank=True)
    SMS = models.EmbeddedModelField(
        model_container = SMSHistory
    )
    App = models.EmbeddedModelField(
        model_container = AppHistory
    )
    Web = models.EmbeddedModelField(
        model_container = WebHistory
    )
    Call = models.EmbeddedModelField(
        model_container = CallHistory
    )


class sanpham(models.Model):
    MaSP = models.CharField(max_length=100)
    TenSP = models.CharField(max_length=100)
    NhaSX = models.CharField(max_length=100)
    LoaiSP = models.CharField(max_length=100)
    LoaiHang = models.IntegerField(default=0)
    NgayTao = models.DateField(default=datetime.date.today)
    LoaiHinhDN = models.CharField(max_length=100)
    MaCapPhep = models.CharField(max_length=100)
    GiayPhep = models.CharField(max_length=100)
    NgayCap = models.CharField(max_length=100)
    CapBoi = models.CharField(max_length=100)
    XuatXuSP = models.CharField(max_length=100)


class SPofDN(models.Model):
    MaDN = models.CharField(max_length=100)
    SanPham = models.EmbeddedModelField(
        model_container = sanpham
    )

class khotemact(models.Model):
    MaTem=models.CharField(max_length=30)
    MaDL=models.CharField(max_length=30)
    Serino=models.CharField(max_length=100)
    MaSP = models.CharField(max_length=100)
    NgayKichHoat=models.DateTimeField()
    SeriTem=models.CharField(max_length=100)

class thamso(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    value=models.IntegerField(default=0)


class imagefile(models.Model):
    anh=models.ImageField(upload_to='media/',null=True,blank=True)
    chuthich=models.TextField(default=' ')

class news(models.Model):
    title=models.TextField()
    ngaydang=models.DateField(auto_now_add=True)
    views=models.IntegerField(default=0)
    content=models.TextField()

vtrue-master/website/forms.py
from django import forms
from .models import History

class CountForm(forms.ModelForm):
    class Meta:
        model=History
        fields=('MaTem',)
        widgets={
            'MaTem':forms.TextInput(attrs={'id':'txtCheck','name':"txtCheck" ,'type':"text",'placeholder':'Nhập mã phủ cào trên tem'}),
        }

vtrue-master/website/views.py
from django.shortcuts import render, redirect
from user.models import vtrueUser
from website.models import History, SPofDN, khotemact, SMSHistory, AppHistory, WebHistory, CallHistory,news as tintuc,imagefile
from django.contrib.auth import authenticate
from django.urls import reverse
import csv
from django.views import View
from django.http import HttpResponse
from .forms import CountForm
from djongo import models
from django.http import HttpResponse
import xlwt
# Create your views here.


def main(request):
    return render(request, 'website/main.html')


def intro(request):
    return render(request, 'website/intro.html')


def news(request):
    a=tintuc.objects.all()[0]
    print(a.content)
    print(a.content.split('@@@'))
    arr=a.content.split('@@@')
    mylist=[]
    for x in arr:
        print(x)
        print("media/{}".format(x))
        b=imagefile.objects.filter(anh='media/{}'.format(x))
        if len(b)>0:
            mylist.append({'check':'1','value':b[0].anh,'chuthich':b[0].chuthich})
            print('anh b',b[0].anh)
        else:
            mylist.append({'check':'0','value':x})
    print('my list',mylist)
    return render(request, 'website/news.html',{'cl':mylist})


def company(request):
    return render(request, 'website/company.html')


def feedback(request):
    return render(request, 'website/feedback.html')


def register(request):
    return render(request, 'website/register.html')


def sign_in(request):
    return render(request, 'website/sign-in.html')


class DSSP:
    def __init__(self, tenSP, count):
        self.tenSP = tenSP
        self.count = count


def count(request):
    if request.user.is_authenticated:
        user1 = vtrueUser.objects.get(TenTK=request.user)
        print('user ne', user1.MaDN)
        item = SPofDN.objects.filter(MaDN=user1.MaDN)

        list = []
        for sp in item:
            i = sp.SanPham
            k = i.MaSP
            toCount = History.objects.filter(MaSP=k)
            print(toCount)
            count = 0
            for x in toCount:
                print(x.SMS.Count)
                count = x.SMS.Count + x.Web.Count + x.Call.Count + x.App.Count

            list.append(DSSP(i.TenSP, count))

        return render(request, 'website/VTrue Service.html', {'username': request.user, 'count': list})

    else:
        return HttpResponse('sai')


class check(View):
    def get(self, request):
        return render(request, 'website/main.html')

    def post(self, request):
        matem = request.POST.get('txtCheck')
        print(matem)
        temp = khotemact.objects.filter(MaTem=matem)
        if len(temp)==0:
            return HttpResponse('Hàng Fake')
        else:
            print(temp[0])
            tim = History.objects.filter(MaTem=temp[0].MaTem)
            if len(tim) == 0:
                them = History.objects.create(MaTem=temp[0].MaTem, MaSP='123',
                    SMS=SMSHistory.objects.get_or_create(
                        ThoiGian='2010-1-1',
                        SoDienThoai='12324',
                        SeriNo='12343',
                        Count=0
                )[0],
                    App=AppHistory.objects.get_or_create(
                        ThoiGian='2010-1-1',
                        DiaChiIP='1',
                        SoDienThoai='12324',
                        SeriNo='12343',
                        Count=0
                )[0],
                    Web=WebHistory.objects.get_or_create(
                        ThoiGian='2010-1-1',
                        DiaChiIP='1',
                        SoDienThoai='12324',
                        SeriNo='12343',
                        Count=1
                )[0],
                    Call=CallHistory.objects.get_or_create(
                        ThoiGian='2010-1-1',
                        SoDienThoai='12324',
                        SeriNo='12343',
                        Count=0
                )[0]
                )

                them.save()
            else:
                History.objects.filter(MaTem=temp[0].MaTem).update(
                    Web={'Count': tim[0].Web.Count+1})
                if tim[0].SMS.Count + tim[0].Web.Count + tim[0].Call.Count + tim[0].App.Count > 4:
                    return HttpResponse('Cảnh báo')
                else:
                    return HttpResponse('oke')


def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="users.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Users')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['so tt', 'ten san pham', 'luot tra cuu',  ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    # get list
    user1 = vtrueUser.objects.get(TenTK=request.user)
    print('user ne', user1.MaDN)
    item = SPofDN.objects.filter(MaDN=user1.MaDN)

    list = []
    for sp in item:
        i = sp.SanPham
        k = i.MaSP
        toCount = History.objects.filter(MaSP=k)
        print(toCount)
        count = 0
        for x in toCount:
            print(x.SMS.Count)
            count = x.SMS.Count + x.Web.Count + x.Call.Count + x.App.Count

        list.append(DSSP(i.TenSP, count))

    rows = list
    for row in rows:
        row_num += 1
        ws.write(row_num, 0, row_num, font_style)
        ws.write(row_num, 1, row.tenSP, font_style)
        ws.write(row_num, 2, row.count, font_style)


    wb.save(response)
    return response

vtrue-master/website/templates/website/VTrue Service.html
{% load static %}
<!DOCTYPE HTML>
<!-- saved from url=(0036)http://xacthuc.chinhphu.vn/ -->
<!DOCTYPE html PUBLIC "" ""><!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]--><!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]--><!--[if !(IE 7) | !(IE 8)  ]><!--><HTML 
lang="en-US"><!--<![endif]--><HEAD><META content="IE=11.0000" 
http-equiv="X-UA-Compatible">
 <meta http-equiv="content-type" content="text/html; charset=UTF-8">
       <meta name="Googlebot" content="index, follow"> <link rel="SHORTCUT ICON" href="link_ttdtcp/favicon.ico"> 
  
	<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<!DOCTYPE HTML>
<!-- saved from url=(0036)http://xacthuc.chinhphu.vn/ -->
<!DOCTYPE html PUBLIC "" ""><!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]--><!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]--><!--[if !(IE 7) | !(IE 8)  ]><!--><HTML 
lang="en-US"><!--<![endif]--><HEAD><META content="IE=11.0000" 
http-equiv="X-UA-Compatible">
<META name="viewport" content="width=device-width"> <TITLE>VTrue Service</TITLE> <LINK href="http://gmpg.org/xfn/11" rel="profile"> <LINK href="http://xacthuc.chinhphu.vn" 
rel="pingback"> <!-- Styles --> <LINK href="{% static 'css/aftersignin/normalize.css' %}"
rel="stylesheet"> <LINK href="{% static '/css/aftersignin/main.css' %}" rel="stylesheet">
<LINK title="Xác thực VTrue" href="http://xacthuc.chinhphu.vn/" 
rel="alternate" type="application/rss+xml"> <LINK title="Xác thực VTrue" 
href="http://xacthuc.chinhphu.vn/" rel="alternate" type="application/rss+xml"> 
<LINK title="Xác thực VTrue" href="http://xacthuc.chinhphu.vn" 
rel="alternate" type="application/rss+xml">		 
<SCRIPT type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"concatemoji":"http:\/\/xacthuc.chinhphu.vn\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.2.1"}};
			!function(a,b,c){function d(a){var c=b.createElement("canvas"),d=c.getContext&&c.getContext("2d");return d&&d.fillText?(d.textBaseline="top",d.font="600 32px Arial","flag"===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f;c.supports={simple:d("simple"),flag:d("flag")},c.supports.simple&&c.supports.flag||(f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
		</SCRIPT>
		 
<STYLE type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</STYLE>
 <LINK id="formidable-css" href="{% static '/css/aftersignin/formidablepro.css' %}" rel="stylesheet"
type="text/css" media="all"> <LINK id="twentytwelve-fonts-css" href="{% static 'css/aftersignin/css.css' %}"
rel="stylesheet" type="text/css" media="all"> <LINK id="twentytwelve-style-css" 
href="{% static 'css/aftersignin/style.css' %}" rel="stylesheet" type="text/css" media="all"> <!--[if lt IE 9]>
<link rel='stylesheet' id='twentytwelve-ie-css'  href='http://xacthuc.chinhphu.vn/wp-content/themes/trueblue/css/ie.css?ver=20121010' type='text/css' media='all' />
<![endif]--> 
<SCRIPT src="{% static 'js/aftersignin/jquery.js' %}" type="text/javascript"></SCRIPT>
 
<SCRIPT src="{% static 'js/aftersignin/jquery-migrate.min.js' %}" type="text/javascript"></SCRIPT>
 <LINK title="RSD" href="http://xacthuc.chinhphu.vn/" 
rel="EditURI" type="application/rsd+xml"> <LINK href="http://xacthuc.chinhphu.vn/" 
rel="wlwmanifest" type="application/wlwmanifest+xml"> 
<META name="GENERATOR" content="MSHTML 11.00.9600.17728"> <LINK href="http://xacthuc.chinhphu.vn/" 
rel="canonical"> <LINK href="http://xacthuc.chinhphu.vn/" rel="shortlink">
	 
<STYLE type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</STYLE>
 <!-- Typekit --> 
<SCRIPT src="{% static 'js/aftersignin/iji7qlc.js' %}" type="text/javascript"></SCRIPT>
 
<SCRIPT type="text/javascript">try{Typekit.load();}catch(e){}</SCRIPT>
 <!-- Modernizr --> 
<SCRIPT src="{% static 'js/aftersignin/modernizr-2.6.2.min.js' %}"></SCRIPT>
 
<SCRIPT type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'xxxxxx']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

</SCRIPT>
 <SCRIPT src="{% static 'js/aftersignin/jquery.easing.1.3.js' %}"></SCRIPT>
 <!-- Transit --> 
<SCRIPT src="{% static 'js/aftersignin/jquery.transit.min.js' %}"></SCRIPT>
 <!-- Placeholder --> 
<SCRIPT src="{% static 'js/aftersignin/jquery.placeholder.js' %}"></SCRIPT>
 <!-- Cycles --> 
<SCRIPT src="{% static 'js/aftersignin/jquery.cycle.all.min.js' %}"></SCRIPT>
 <!-- Colorbox --> 
<SCRIPT src="{% static 'js/aftersignin/jquery.colorbox-min.js' %}"></SCRIPT>
 <LINK href="{% static 'css/aftersignin/colorbox.css' %}" rel="stylesheet" media="screen">
	</head>

	<!-- JS --> 
<SCRIPT src="{% static 'js/aftersignin/plugins.js' %}"></SCRIPT>
 
<SCRIPT src="{% static 'js/aftersignin/main.js' %}"></SCRIPT>
 
<SCRIPT src="{% static 'js/aftersignin/comment-reply.min.js' %}" type="text/javascript"></SCRIPT>
 
<SCRIPT src="{% static 'js/aftersignin/navigation.js' %}" type="text/javascript"></SCRIPT>

 </HEAD> 
 


<script language=javascript src="fnc_Validdates.js"></script>
<script language=javascript src="date-picker.js"></script>
<script language="javascript" type=""> 

function comboChange(){
    document.parentForm.submit();
  }
function checkValues(){
if (document.parentForm.FDate.value==""){
    alert("Chưa nhập ngày");
    document.parentForm.FDate.focus();
    return false;
  }
 else if (document.parentForm.TDate.value.length!=10){
    alert("Ngày dạng: mm/dd/yyyy");
    document.parentForm.TDate.focus();
    return false;
  }
 
 else if (document.parentForm.FDate.value!="" && document.parentForm.FDate.value.length!=10){
    alert("Ngày dạng: mm/dd/yyyy");
    document.parentForm.FDate.focus();
    return false;
  }
  else if(document.parentForm.FDate.value.substring(0,2)!=document.parentForm.TDate.value.substring(0,2)){
  alert("Tra cứu từ ngày tới ngày phải nằm trong một tháng !");
  return false;
  }
  else if (document.parentForm.sdt.value==""){
    alert("Nhập số mobile!");
    document.parentForm.sdt.focus();
    return false;
  }
  /*if (isNaN(document.parentForm.sdt.value)){
    alert("Số mobile nhập không đúng!");
    document.parentForm.User_ID.focus();
    return false;
  }*/
  /*else if (document.parentForm.sdt.value.length!=11){
    alert("Số mobile sai: 849xxxxxxxx");
    document.parentForm.sdt.focus();
    return false;
  }*/
  return true;
}
</script>

<BODY class="home page page-id-7 page-template page-template-page-templates page-template-front-page page-template-page-templatesfront-page-php template-front-page custom-font-enabled single-author">
<div class="wrapper header">
<div class="container">
<div id="header">
<div class="logo"><A href="/?v=1"><IMG alt="Xác thực điện tử VTrue" src="{% static 'img/vtrue_logo.png' %}"  border="0"></A></div>
<div class="info">
<P>Hotline<SPAN>1900-6609</SPAN></P></div>
<div class="banner"><IMG alt="Over 35 years experience" src="{% static 'img/experience-banner.png' %}"></div>
<div id="nav">
<div class="menu-main-container">
<ul class="nav-menu" id="menu-main">
  <li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-29"
  id="menu-item-29"><a href="/?v=1">Trang chủ</a></li>
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37" id="menu-item-37"><a href="/doanhnghiep/?v=20">
	tra cứu xác thực</a></li>
  <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"  id="menu-item-53">
  <a href="/doanhnghiep/?v=23">báo cáo bảo hành</a>
  </li>
  <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"  id="menu-item-53">
  <a href="/doanhnghiep/?v=24">báo cáo tích điểm</a>
</li>

</ul></div></div>
  <!-- /nav -->         
  </div><!-- /header -->
</div><!-- /container -->
</div><!-- /wrapper -->		<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<div class="wrapper content">

    <div class="container">
	    	
        <div class="holder">
        
            <div class="column wide">
                	
                <div class="spacing">

                    <div id="content">

		<header class="entry-header">
			<h2 class="entry-title">TÌM KIẾM THÔNG TIN VỀ NGƯỜI DÙNG ĐÃ TRA CỨU </h2>
		</header>
			 <table border=0>
            <form method="post" name="frmsearch" onsubmit="return frmRegister_onsubmit1()"action="/doanhnghiep/?v=22">  	 	
            <tr>
                <td>Nhập số điện thoại:<input type="text" name="sodienthoai" value="" size="15">
				<input type="submit" value="  Tìm kiếm   "></td>
            </tr>			
        </form>
            </table>
		<script language=javascript>
	function frmRegister_onsubmit1()
	{	
	with (frmsearch)
	{	
		{
		if ((sodienthoai.value=="0")||(sodienthoai.value.length<10))
		{
		alert("Ðề nghị nhập số điện thoại");
		sodienthoai.focus();
		return false;
		}
		
		}
	}
	return true;
	}
	</script>	
	<article id="post-11" class="post-11 page type-page status-publish hentry">
		<header class="entry-header">
			<h2 class="entry-title">BẢNG KÊ TỔNG HỢP THEO USERNAME: {{username}} </h2>
		</header>

		<div class="entry-content">

		<table cellpadding="1" cellspacing="1" width="60%" border="0" class=adv align=center>
	<tr align=left bgcolor=LightGrey>
		<td height=25><b>Số TT</b></td>
		<td><b>Tên sản phẩm </b></td>
		<td><b>Tổng tra cứu </b></td>
		<td><b>Xem chi tiết </b></td>
	</tr>	

			{% for i in count %}
			<tr height=18 bgcolor= >
				<td>1</td>
				<td><a href="/doanhnghiep/?x=amdD2P4vEE">{{i.tenSP}}</a>


		</td>
		<td valign="top">{{i.count}}</td>
		<td valign="top"><a href="/doanhnghiep/?v=21&c=amdD2P4vEE"> Chi tiết</a></td>
	</tr>



			{% endfor %}
	<a href="{% url 'website:export_users_xls' %}">Export all users</a>





</table>

					</div><!-- .entry-content -->
		<footer class="entry-meta">
					</footer><!-- .entry-meta -->
	</article><!-- #post -->
				           
			            
                    </div>  
                                                
                </div><!-- /spacing -->
                    
            </div><!-- /column -->
         
        </div><!-- /holder -->                    

    </div><!-- /container -->

</div><!-- /wrapper -->
		
		<!- --#include file=footer.htm--> 

vtrue-master/website/templates/website/sign-in.html
{% extends 'website/base.html' %}
{% block sign-in %}

 <div class="rightcontent">
  <div class="popupdangnhapInner">
    <div class="dnOut">
      <ul class="ul_breadcrumb">
                        <li><a href="/main">Trang chủ</a></li>
                        <li><a>Đăng nhập</a></li>
                    </ul>
      <form action="{% url 'user:signin' %}" method="post" name="login" onsubmit="return frmRegister_onsubmit()">
        {% csrf_token %}
        <ul class="dn_pp_lst">
          <li>
            <input type="text" id="txt" name="userName" placeholder="E-mail" class="in_dkf_r" />
          </li>
          <li>
            <input type="password" id="txt1" name="password" placeholder="Mật khẩu" class="in_dkf_r" />&nbsp;
			<input name="token" hidden type="text" size="60" maxlength=200 value="EE725CCAF196EF907509C3A28F89FD8534356B29E1B9527F5040B045619E59BC" ID="Text4">
          </li>
          <li class="pd2 clearfix">&nbsp; </li>

          <li class="clearfix">
                            <button class="btn_gen"><span>Đăng nhập</span></button>

          </li>
        </ul>
      </form>
    </div>
  </div>
</div>
<script language=javascript>
	function frmRegister_onsubmit()
	{
	with (login)
	{
		if ((txtUsername.value=="")||(txtUsername.value.indexOf(" ")>0)||(txtUsername.value>40))
		{
		alert("Nhập Tên truy cập");
		txtUsername.focus();
		return false;
		}
		if ((txtPassword.value=="")||(txtPassword.value.length<5))
		{
		alert("Đề nghị nhập mật khẩu");
		txtPassword.focus();
		return false;
		}
	}
	return true;
	}
	</script>
{% endblock %}